// Central bird catalog
// Each object here is one species template, not one individual bird.
// The save system clones this library, then tracks player-specific fields like count and variantCounts separately.
const BIRD_LIBRARY = [
  {
    id: "crow",
    species: "American Crow",
    visitorsPerDay: 1,
    diet: "seeds",
    rarity: "Common",
    acquired: true,
    image: "/Resources/Bird Images/crow_frontpage.png",
    call: "/Resources/Calls/crow.wav",
    nativeHabitat: "City Living",
    scientificName: "Corvus brachyrhynchos",
    habitatScale: 0.8
  },
  {
    id: "pigeon",
    species: "Rock Pigeon",
    visitorsPerDay: 2,
    diet: "seeds",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/pigeon.png",
    call: "/Resources/Calls/pigeon.wav",
    nativeHabitat: "City Living",
    scientificName: "Columba livia"
  },
  {
    id: "kestrel",
    species: "American Kestrel",
    visitorsPerDay: 3,
    twigsPerSecond: 0.04,
    diet: "grubs",
    rarity: "Uncommon",
    acquired: false,
    image: "/Resources/Bird Images/kestrel.png",
    call: "/Resources/Calls/kestrel.wav",
    nativeHabitat: "City Living",
    scientificName: "Falco sparverius",
    habitatScale: 0.8
  },
  {
    id: "bluejay",
    species: "Blue Jay",
    visitorsPerDay: 1,
    twigsPerSecond: 0.06,
    diet: "seeds",
    rarity: "Uncommon",
    acquired: false,
    image: "/Resources/Bird Images/bluejay.png",
    call: "/Resources/Calls/bluejay.wav",
    nativeHabitat: "City Living",
    scientificName: "Cyanocitta cristata"
  },
  {
    id: "mourningdove",
    species: "Mourning Dove",
    visitorsPerDay: 1,
    seedsPerSecond: 0.1,
    diet: "seeds",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/mourningdove.png",
    call: "/Resources/Calls/mourningdove.wav",
    nativeHabitat: "City Living",
    scientificName: "Zenaida macroura"
  },
  {
    id: "pileatedwoodpecker",
    species: "Pileated Woodpecker",
    visitorsPerDay: 1,
    twigsPerSecond: 0.06,
    grubsPerSecond: 0.06,
    abilities: ["treePeck"],
    diet: "grubs",
    rarity: "Rare",
    acquired: false,
    image: "/Resources/Bird Images/pileatedwoodpecker.png",
    call: "/Resources/Calls/pileatedwoodpecker.mp3",
    nativeHabitat: "City Living",
    scientificName: "Dryocopus pileatus",
    habitatScale: 1.2
  },
  {
    id: "cardinal",
    species: "Northern Cardinal",
    visitorsPerDay: 5,
    abilities: ["dimorphic"],
    diet: "seeds",
    rarity: "Rare",
    acquired: false,
    variantImages: {
      male: "/Resources/Bird Images/cardinalMale.png",
      female: "/Resources/Bird Images/cardinalFemale.png"
    },
    habitatVariantScales: {
      male: 1.1,
      female: 1
    },
    call: "/Resources/Calls/cardinal.mp3",
    nativeHabitat: "City Living",
    scientificName: "Cardinalis cardinalis",
    habitatScale: 1.2
  },
  {
    id: "nuthatch",
    species: "White-Breasted Nuthatch",
    visitorsPerDay: 2,
    diet: "grubs",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/nuthatch.png",
    call: "/Resources/Calls/nuthatch.wav",
    nativeHabitat: "City Living",
    scientificName: "Sitta carolinensis",
  },
  {
    id: "screechowl",
    species: "Eastern Screech Owl",
    grubsPerSecond: 0.1,
    abilities: ["overseer"],
    diet: "grubs",
    rarity: "Epic",
    acquired: false,
    image: "/Resources/Bird Images/screechowl.png",
    call: "/Resources/Calls/screechowl.wav",
    nativeHabitat: "City Living",
    scientificName: "Megascops asio",
  },
  {
    id: "nighthawk",
    species: "Common Nighthawk",
    grubsPerSecond: 0.02,
    abilities: ["nocturnal"],
    diet: "grubs",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/nighthawk.png",
    call: "/Resources/Calls/nighthawk.wav",
    nativeHabitat: "City Living",
    scientificName: "Chordeiles minor",
  },
  {
    id: "shrike",
    species: "Loggerhead Shrike",
    diet: "mice",
    rarity: "Legendary",
    acquired: false,
    image:"/Resources/Bird Images/shrike.png",
    call: "/Resources/Calls/shrike.mp3",
    nativeHabitat: "The Hollow",
    scientificName: "Lanius ludovicianus",
  },
  {
    id: "cowbird",
    species: "Brown-Headed Cowbird",
    diet: "seeds",
    abilities: ["parasite"],
    rarity: "Uncommon",
    acquired: false,
    image: "/Resources/Bird Images/cowbird.png",
    call: "/Resources/Calls/cowbird.mp3",
    nativeHabitat: "City Living",
    scientificName: "Molothrus ater",
  },
  {
    id: "redTailedHawk",
    species: "Red-Tailed Hawk",
    twigsPerSecond: 0.1,
    bonusPeachTree: 2,
    habitatScale: 1.6,
    diet: "mice",
    rarity: "Epic",
    abilities: ["predator"],
    acquired: false,
    image: "/Resources/Bird Images/redTailedHawk.png",
    call: "/Resources/Calls/redTailedHawk.wav",
    nativeHabitat: "City Living",
    scientificName: "Buteo jamaicensis",
  },
  {
    id: "mallard",
    species: "Mallard",
    diet: "seeds",
    rarity: "Common",
    abilities: ["dimorphic"],
    acquired: false,
    visitorsPerDay: 2,
    variantImages: {
      male: "/Resources/Bird Images/mallardMale.png",
      female: "/Resources/Bird Images/mallardFemale.png"
    },
    habitatVariantScales: {
      male: 1.3,
      female: 1
    },
    call: "/Resources/Calls/mallard.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Anas platyrhynchos"
  },
  {
    id: "goose",
    species: "Canada Goose",
    diet: "seeds",
    rarity: "Common",
    visitorsPerDay: 2,
    seedsPerSecond: 0.1,
    image: "/Resources/Bird Images/goose.png",
    call: "/Resources/Calls/goose.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Branta canadensis",
    habitatScale: 1.3
  },
  {
    id: "sandpiper",
    species: "Spotted Sandpiper",
    diet: "grubs",
    rarity: "Common",
    twigsPerSecond: 0.04,
    image: "/Resources/Bird Images/sandpiper.png",
    call: "/Resources/Calls/sandpiper.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Actitis macularius"
  },
  {
    id: "nightheron",
    species: "Black-Crowned Night Heron",
    diet: "fish",
    rarity: "Uncommon",
    visitorsPerDay: 4,
    abilities: ["nocturnal"],
    image: "/Resources/Bird Images/nightHeron.png",
    call: "/Resources/Calls/nightHeron.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Nycticorax nycticorax"
  },
  {
    id: "greenheron",
    species: "Green Heron",
    diet: ["fish", "grubs"],
    rarity: "Rare",
    grubsPerSecond: 0.04,
    abilities: ["baitfisher"],
    image: "/Resources/Bird Images/greenHeron.png",
    call: "/Resources/Calls/greenHeron.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Butorides virescens"
  },
  {
    id: "muteswan",
    species: "Mute Swan",
    diet: "seeds",
    rarity: "Epic",
    visitorsPerDay: 5,
    abilities: ["mascot"],
    image: "/Resources/Bird Images/muteSwan.png",
    call: "/Resources/Calls/muteSwan.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Cygnus olor"
  },
  {
    id: "killdeer",
    species: "Killdeer",
    diet: "grubs",
    rarity: "Common",
    twigsPerSecond: 0.02,
    grubsPerSecond: 0.01,
    image: "/Resources/Bird Images/killdeer.png",
    call: "/Resources/Calls/killdeer.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Charadrius vociferus"
  },
  {
    id: "osprey",
    species: "Osprey",
    diet: "fish",
    rarity: "Rare",
    abilities: ["globalist"],
    visitorsPerDay: 3,
    image: "/Resources/Bird Images/osprey.png",
    call: "/Resources/Calls/osprey.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Pandion haliaetus"
  },
  {
    id: "coot",
    species: "American Coot",
    diet: "seeds",
    rarity: "Uncommon",
    seedsPerSecond: 0.2,
    image: "/Resources/Bird Images/coot.png",
    call: "/Resources/Calls/coot.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Fulica americana"
  },
  {
    id: "kingfisher",
    species: "Belted Kingfisher",
    diet: "fish",
    rarity: "Epic",
    abilities: ["spearfishing"],
    image: "/Resources/Bird Images/kingfisher.png",
    call: "/Resources/Calls/kingfisher.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Megaceryle alcyon"
  },
  {
    id: "cormorant",
    species: "Double-Breasted Cormorant",
    diet: "fish",
    rarity: "Legendary",
    abilities: ["deepSeaDiver"],
    visitorsPerDay: 5,
    seedsPerSecond: 0.5,
    image: "/Resources/Bird Images/cormorant.png",
    call: "/Resources/Calls/cormorant.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Nannopterum auritum"
  },
  {
    id: "avocet",
    species: "American Avocet",
    diet: "grubs",
    rarity: "Epic",
    abilities: ["mudSweeper"],
    grubsPerSecond: 0.05,
    image: "/Resources/Bird Images/avocet.png",
    call: "/Resources/Calls/avocet.wav",
    nativeHabitat: "Urban Waters",
    scientificName: "Recurvirostra americana"
  },
  {
    id: "harrier",
    species: "Northern Harrier",
    diet: "mice",
    rarity: "Epic",
    abilities: ["overseer"],
    twigsPerSecond: 0.08,
    visitorsPerDay: 5,
    bonusPearTree: 1,
    image: "/Resources/Bird Images/harrier.png",
    call: "/Resources/Calls/harrier.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Circus hudsonius"
  },
  {
    id: "grebe",
    species: "Pied-billed Grebe",
    diet: ["fish", "grubs"],
    rarity: "Common",
    grubsPerSecond: 0.01,
    visitorsPerDay: 1,
    image: "/Resources/Bird Images/grebe.png",
    call: "/Resources/Calls/grebe.mp3",
    nativeHabitat: "Urban Waters",
    scientificName: "Podilymbus podiceps"
  }
];
