// Central bird catalog. Add new species here and the rest of the game reads from it.
const BIRD_LIBRARY = [
  {
    id: "crow",
    species: "American Crow",
    visitorsPerDay: 1,
    diet: "seeds",
    rarity: "Common",
    acquired: true,
    image: "/Resources/Bird Images/crow_frontpage.png",
    call: "/Resources/Calls/crow.wav",
    nativeHabitat: "City Living",
    scientificName: "Corvus brachyrhynchos"
  },
  {
    id: "pigeon",
    species: "Rock Pigeon",
    visitorsPerDay: 2,
    diet: "seeds",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/pigeon.png",
    call: "/Resources/Calls/pigeon.wav",
    nativeHabitat: "City Living",
    scientificName: "Columba livia"
  },
  {
    id: "kestrel",
    species: "American Kestrel",
    visitorsPerDay: 3,
    twigsPerSecond: 0.04,
    diet: "grubs",
    rarity: "Uncommon",
    acquired: false,
    image: "/Resources/Bird Images/kestrel.png",
    call: "/Resources/Calls/kestrel.wav",
    nativeHabitat: "City Living",
    scientificName: "Falco sparverius"
  },
  {
    id: "bluejay",
    species: "Blue Jay",
    visitorsPerDay: 1,
    twigsPerSecond: 0.08,
    diet: "seeds",
    rarity: "Uncommon",
    acquired: false,
    image: "/Resources/Bird Images/bluejay.png",
    call: "/Resources/Calls/bluejay.wav",
    nativeHabitat: "City Living",
    scientificName: "Cyanocitta cristata"
  },
  {
    id: "mourningdove",
    species: "Mourning Dove",
    visitorsPerDay: 1,
    seedsPerSecond: 0.1,
    diet: "seeds",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/mourningdove.png",
    call: "/Resources/Calls/mourningdove.png",
    nativeHabitat: "City Living",
    scientificName: "Zenaida macroura"
  },
  {
    id: "pileatedwoodpecker",
    species: "Pileated Woodpecker",
    visitorsPerDay: 1,
    twigsPerSecond: 0.06,
    grubsPerSecond: 0.25,
    abilities: ["treePeck"],
    diet: "grubs",
    rarity: "Rare",
    acquired: false,
    image: "/Resources/Bird Images/pileatedwoodpecker.png",
    call: "/Resources/Calls/pileatedwoodpecker.mp3",
    nativeHabitat: "City Living",
    scientificName: "Dryocopus pileatus",
  },
  {
    id: "cardinal",
    species: "Northern Cardinal",
    visitorsPerDay: 10,
    abilities: ["dimorphic"],
    diet: "seeds",
    rarity: "Rare",
    acquired: false,
    variantImages: {
      male: "/Resources/Bird Images/cardinalMale.png",
      female: "/Resources/Bird Images/cardinalFemale.png"
    },
    call: "/Resources/Calls/cardinal.mp3",
    nativeHabitat: "City Living",
    scientificName: "Cardinalis cardinalis",
  },
  {
    id: "nuthatch",
    species: "White-Breasted Nuthatch",
    visitorsPerDay: 2,
    diet: "grubs",
    rarity: "Common",
    acquired: false,
    image: "/Resources/Bird Images/nuthatch.png",
    call: "/Resources/Calls/nuthatch.wav",
    nativeHabitat: "City Living",
    scientificName: "Sitta carolinensis",
  }
];
