// Species-specific upgrades live separately from birds.js and upgrades.js so
// bird identity data stays lightweight while species progression stays easy to
// author one bird at a time.
//
// Placeholder template for future upgrades:
// {
//   id: "birdIdUpgradeId",
//   name: "Upgrade Name",
//   order: 1,
//   oneTime: true,
//   requirements: {
//     birds: {
//       birdId: 5
//     }
//   },
//   costs: {
//     coins: 2500
//   },
//   description: "What this upgrade will eventually do."
// }

const SPECIES_UPGRADE_LIBRARY = {
  // City Living
  crow: {
    visible: true,
    upgrades: [
      {
      id: "crowMurderParty",
      name: "Murder Party",
      order: 1,
      oneTime: true,
      requirements: {
        birds: {
          crow: 3
        }
      },
      costs: {
        coins: 100
      },
      description: "Doubles visitors per day generated by the American Crow",
      modifyVisitorsPerDay(visitorRate, context) {
        if (context.bird.id === "crow") {
          return visitorRate * 2;
        }

        return visitorRate;
      }
    },
    {
      id: "crowPickpocket",
      name: "Pickpocket",
      order: 2,
      oneTime: true,
      grantedAbilities: ["pickpocket"],
      requirements: {
        birds: {
          crow: 5
        }
      },
      costs: {
        coins: 1000
      },
      description: "The American Crow now has the ability pickpocket!"
    },
    {
      id: "crowHandyman",
      name: "Handyman",
      order: 3,
      oneTime: true,
      requirements: {
        birds: {
          crow: 10
        }
      },
      costs: {
        coins: 5000
      },
      description: "Obtaining a crow with a seed ticket refunds the ticket.",
      onBirdCaught(gameState, context) {
        if (
          context.bird &&
          context.bird.id === "crow" &&
          context.baitType === "seeds" &&
          context.usedSeedTicket
        ) {
          addItemCount(gameState, "seedbaitticket", 1);
        }
      }
    },
    {
      id: "crowRichClients",
      name: "Rich Clients",
      order: 4,
      oneTime: true,
      requirements: {
        birds: {
          crow: 15
        }
      },
      costs: {
        coins: 7500
      },
      description: "Improves rewards obtained via the Pickpocket ability.",
      modifyPickpocketReward(rewardEntry) {
        if (!rewardEntry) {
          return rewardEntry;
        }

        return {
          ...rewardEntry,
          amount: Math.round(rewardEntry.amount * 1.5)
        };
      }
    },
    {
      id: "crowScavenger",
      name: "Scavenger",
      order: 5,
      oneTime: true,
      requirements: {
        birds: {
          crow: 20
        }
      },
      costs: {
        coins: 10000
      },
      description: "Catching a crow with seed bait refunds the used seeds.",
      onBirdCaught(gameState, context) {
        if (
          context.bird &&
          context.bird.id === "crow" &&
          context.baitType === "seeds" &&
          context.spentSeedCost > 0
        ) {
          gameState.seeds += context.spentSeedCost;
        }
      }
    },
    {
      id: "crowOohShiny",
      name: "Ooh Shiny",
      order: 6,
      oneTime: true,
      requirements: {
        birds: {
          crow: 25
        }
      },
      costs: {
        coins: 15000
      },
      description: "Doubles coin rewards from Pickpocket.",
      modifyPickpocketReward(rewardEntry) {
        if (!rewardEntry || rewardEntry.resourceKey !== "coins") {
          return rewardEntry;
        }

        return {
          ...rewardEntry,
          amount: rewardEntry.amount * 2
        };
      }
    },
    {
      id: "crowIrridescence",
      name: "Irridescence",
      order: 7,
      oneTime: true,
      requirements: {
        birds: {
          crow: 30
        }
      },
      costs: {
        coins: 20000
      },
      description: "Catching a crow rewards 5 scrap.",
      onBirdCaught(gameState, context) {
        if (context.bird && context.bird.id === "crow") {
          gameState.scrap += 5;
        }
      }
    },
    {
      id: "crowMastermind",
      name: "Mastermind",
      order: 8,
      oneTime: true,
      requirements: {
        birds: {
          crow: 50
        }
      },
      costs: {
        coins: 50000
      },
      description: "Improves odds of catching legendary birds (+1% Legendary, -1% Common).",
      modifyRarityWeights(rarityWeights) {
        return {
          ...rarityWeights,
          Common: rarityWeights.Common - 1,
          Legendary: rarityWeights.Legendary + 1
        };
      }
      }
    ]
  },
  pigeon: {
    visible: true,
    upgrades: [
      {
        id: "pigeonGregarious",
        name: "Gregarious",
        order: 1,
        oneTime: true,
        requirements: { birds: { pigeon: 5 } },
        costs: { coins: 2500 },
        description: "Every additional pigeon after the fifth increases base visitors per day by 5%",
        modifyVisitorsPerDay(visitorRate, context) {
          const additionalPigeons = Math.max(0, context.bird.count - 5);
          return visitorRate * (1 + (additionalPigeons * 0.05));
        }
      },
       {
        id: "pigeonCropMilk",
        name: "Crop Milk",
        order: 2,
        oneTime: true,
        requirements: { birds: { pigeon: 25 } },
        costs: { coins: 10000 },
        description: "Increases catch rate by 1%",
        modifyCatchRate(catchRate) {
          return catchRate + 0.01;
        }
      }
  ],
},
  kestrel: {
    visible: true,
    upgrades: [
    {
      id: "kestrelFalconry",
      name: "Falconry",
      order: 1,
      oneTime: true,
      requirements: { birds: { kestrel: 25 } },
      costs: { coins: 50000 },
      description: "Awards 1 feeder mouse.",
      onPurchase(gameState) {
        gameState.mice += 1;
      }
    }
  ]
  },
  bluejay: {
    visible: true,
    upgrades: [
      {
        id: "bluejayFrugivory",
        name: "Frugivory",
        order: 1,
        oneTime: true,
        requirements: { birds: { bluejay: 25 } },
        costs: { coins: 50000 },
        description: "Increases tree maximums by 1.",
        modifyTreeMaxCount(maxCount) {
          return maxCount + 1;
        }
      }
    ]
  },
  mourningdove: {
    visible: true,
    upgrades: [
      {
      id: "mourningdoveTurtleWake",
      name: "Turtle Wake",
      order: 2,
      oneTime: true,
      requirements: { birds: { mourningdove: 5 } },
      costs: { coins: 1000 },
      description: "Mourning Doves start generating 2.4 twigs per minute.",
      modifyTwigRatePerMinute(twigRate, context) {
        if (context.bird.id === "mourningdove") {
          return twigRate + 2.4;
        }

        return twigRate;
      }
    },
    {
      id: "mourningdoveSeedDispersal",
      name: "Seed Dispersal",
      order: 1,
      oneTime: true,
      requirements: { birds: { mourningdove: 3 } },
      costs: { coins: 500 },
      description: "Grants a free Pear Tree and increases the Pear Tree max by 1.",
      modifyTreeMaxCount(maxTreeCount, context) {
        if (context.treeKey === "pearTrees") {
          return maxTreeCount + 1;
        }

        return maxTreeCount;
      },
      onPurchase(gameState) {
        gameState.pearTrees += 1;
      }
      }
    ]
  },
  pileatedwoodpecker: {
    visible: true,
    upgrades: [
      {
        id: "pileatedwoodpeckerWoodcarver",
        name: "Woodcarver",
        order: 1,
        oneTime: true,
        requirements: { birds: { pileatedwoodpecker: 10 } },
        costs: { coins: 15000 },
        description: "Decreases sawmill duration by 10%.",
        modifySawmillProcessingDurationMs(processingDurationMs) {
          return processingDurationMs * 0.9;
        }
      },
      {
        id: "pileatedwoodpeckerMonogamist",
        name: "Monogamist",
        order: 2,
        oneTime: true,
        requirements: { birds: { pileatedwoodpecker: 20 } },
        costs: { coins: 50000 },
        description: "Every caught Pileated Woodpecker now comes in a pair."
      }
    ]
  },
  cardinal: {
    visible: true,
    upgrades: [
      {
        id: "cardinalGranivory",
        name: "Granivory",
        order: 2,
        oneTime: true,
        requirements: { birds: { cardinal: 15 } },
        costs: { coins: 10000 },
        description: "Increases seeds from trees by 5%.",
        modifyTreeSeedsPerMinute(treeSeedsPerMinute) {
          return treeSeedsPerMinute * 1.05;
        }
      },
      {
        id: "cardinalColorful",
        name: "Colorful",
        order: 1,
        oneTime: true,
        requirements: { birds: { cardinal: 5 } },
        costs: { coins: 2500 },
        description: "Increases coins per visitor by 10.",
        modifyCoinsPerVisitorRate(coinsPerVisitor) {
          return coinsPerVisitor + 10;
        }
      }
    ]
  },
  nuthatch: {
    visible: true,
    upgrades: [
      {
        id: "nuthatchSquirrelDeterrent",
        name: "Squirrel Deterrent",
        order: 1,
        oneTime: true,
        requirements: { birds: { nuthatch: 5 } },
        costs: { coins: 2500 },
        description: "Nuthatches now generate 3 seeds per minute.",
        modifySeedRatePerMinute(seedRate, context) {
          if (context.bird.id === "nuthatch") {
            return seedRate + 3;
          }

          return seedRate;
        }
      }
    ]
  },
  screechowl: [
    {
      id: "screechowlPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { screechowl: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Eastern Screech Owl."
    }
  ],
  nighthawk: [
    {
      id: "nighthawkPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { nighthawk: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Common Nighthawk."
    }
  ],
  shrike: [
    {
      id: "shrikePlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { shrike: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Loggerhead Shrike."
    }
  ],
  cowbird: {
    visible: true,
    upgrades: [
      {
      id: "cowbirdParasiteUncommon",
      name: "Parasite: Uncommon",
      order: 1,
      oneTime: true,
      requirements: { birds: { cowbird: 5 } },
      costs: { coins: 250 },
      description: "The Brown-Headed Cowbird can now prey on uncommon birds in City Living."
      },
      {
      id: "cowbirdParasiteRare",
      name: "Parasite: Rare",
      order: 1,
      oneTime: true,
      requirements: { birds: { cowbird: 10 } },
      costs: { coins: 5000 },
      description: "The Brown-Headed Cowbird can now prey on rare birds in City Living."
      },
      {
      id: "cowbirdParasiteEpic",
      name: "Parasite: Epic",
      order: 1,
      oneTime: true,
      requirements: { birds: { cowbird: 20 } },
      costs: { coins: 15000 },
      description: "The Brown-Headed Cowbird can now prey on epic birds in City Living."
      },
      {
      id: "cowbirdParasiteInvasive",
      name: "Parasite: Invasive",
      order: 1,
      oneTime: true,
      requirements: { birds: { cowbird: 50 } },
      costs: { coins: 50000 },
      description: "The Brown-Headed Cowbird can now prey on birds in any habitat."
      }
    ],
  },
  redTailedHawk: [
    {
      id: "redTailedHawkPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { redTailedHawk: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Red-Tailed Hawk."
    }
  ],

  // Urban Waters
  mallard: [
    {
      id: "mallardPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { mallard: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Mallard."
    }
  ],
  goose: [
    {
      id: "goosePlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { goose: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Canada Goose."
    }
  ],
  sandpiper: [
    {
      id: "sandpiperPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { sandpiper: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Spotted Sandpiper."
    }
  ],
  nightheron: [
    {
      id: "nightheronPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { nightheron: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Black-Crowned Night Heron."
    }
  ],
  greenheron: [
    {
      id: "greenheronPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { greenheron: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Green Heron."
    }
  ],
  muteswan: [
    {
      id: "muteswanPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { muteswan: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Mute Swan."
    }
  ],
  killdeer: [
    {
      id: "killdeerPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { killdeer: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Killdeer."
    }
  ],
  osprey: [
    {
      id: "ospreyPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { osprey: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Osprey."
    }
  ],
  coot: [
    {
      id: "cootPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { coot: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for American Coot."
    }
  ],
  kingfisher: [
    {
      id: "kingfisherPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { kingfisher: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Belted Kingfisher."
    }
  ],
  cormorant: [
    {
      id: "cormorantPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { cormorant: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Double-Crested Cormorant."
    }
  ],
  avocet: [
    {
      id: "avocetPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { avocet: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for American Avocet."
    }
  ],
  harrier: [
    {
      id: "harrierPlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { harrier: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Northern Harrier."
    }
  ],
  grebe: [
    {
      id: "grebePlaceholderA",
      name: "Placeholder Upgrade",
      order: 1,
      oneTime: true,
      requirements: { birds: { grebe: 5 } },
      costs: { coins: 2500 },
      description: "Placeholder upgrade for Pied-billed Grebe."
    }
  ],
  snowBunting: {
    visible: true,
    upgrades: [
    {
      id: "snowBuntingWeedeater",
      name: "Weedeater",
      order: 1,
      oneTime: true,
      requirements: { birds: { snowBunting: 10 } },
      costs: { coins: 5000 },
      description: "Increases coins per visitor by 10",
      modifyCoinsPerVisitorRate(coinsPerVisitor) {
          return coinsPerVisitor + 10;
        }
    }
  ]
  },
  ptarmigan: {
    visible: true,
    upgrades: [
      {
        id: "ptarmiganPopulationBoom",
        name: "Population Boom",
        order: 1,
        oneTime: true,
        requirements: { birds: { ptarmigan: 10 } },
        costs: { coins: 10000 },
        description: "Changes the Rock Ptarmigan's rarity to Common.",
        onPurchase(gameState) {
          const ptarmiganInFlock = getBirdById(gameState, "ptarmigan");
          if (ptarmiganInFlock) {
            ptarmiganInFlock.rarity = "Common";
          }
        }
      },
      {
        id: "ptarmiganOverpopulation",
        name: "Overpopulation",
        order: 2,
        oneTime: true,
        requirements: { birds: { ptarmigan: 10 } },
        costs: { coins: 15000 },
        description: "Every fifth Rock Ptarmigan catch grants an additional Rock Ptarmigan.",
        onBirdCaught(gameState, context) {
          if (!context || !context.bird || context.bird.id !== "ptarmigan") {
            return;
          }

          const nextCatchCount = getSpeciesUpgradeCounter(gameState, "ptarmiganOverpopulationCaught") + 1;
          setSpeciesUpgradeCounter(gameState, "ptarmiganOverpopulationCaught", nextCatchCount);

          if (nextCatchCount % 5 === 0) {
            const ptarmiganInFlock = getBirdById(gameState, "ptarmigan");
            if (ptarmiganInFlock) {
              addBirdToFlock(gameState, ptarmiganInFlock);
            }
          }
        }
      }
    ]
  },
  dunlin: {
    visible: true,
    upgrades: [
    {
      id: "dunlinGregarious",
      name: "Gregarious",
      order: 1,
      oneTime: true,
      requirements: { birds: { bird: 5 } },
      costs: { coins: 2500 },
      description: "Every additional dunlin after the fifth increases base visitors per day by 5%",
        modifyVisitorsPerDay(visitorRate, context) {
          const additionalDunlins = Math.max(0, context.bird.count - 5);
          return visitorRate * (1 + (additionalDunlins * 0.05));
        },
      }
    ]
  }







};
